### PR TITLE
add multiline support

### LINKED ISSUE #25: add support for newline in prompts
it is impossible to use newline in prompts.

suggested fix: sending the prompt is done by Modifier+Enter as done in messaging apps, such that newline is supported.

Thanks!

### PR DESCRIPTION
**Pull request by monperrus**
fix #25

### CODE REVIEW

**Comment by marcolardera** [comment]
I'm reading the documentation about "multiline=True":

> A side effect of this is that the enter key will now insert a newline instead of accepting and returning the input. The user will now have to press Meta+Enter in order to accept the input. (Or Escape followed by Enter.)

It doesn't seem very intuitive to use. The ideal way I think would be: ENTER --> submit, CRTL+ENTER --> newline

Not sure about that PR, I will think about it for a bit...

**Comment by monperrus** [comment]
Thanks @marcolardera 

One option is that this mode is an option:

    ./chatgpt.py --multiline

I'm using this mode extensively because I write code in the prompt, esp Python code.

**Comment by marcolardera** [comment]
Yes, I like this idea!

**Comment by marcolardera** [comment]
I did that in the last commit: https://github.com/marcolardera/chatgpt-cli/commit/c8212f874665fc0676bc6915c611de6f6ca4b473

**Comment by monperrus** [comment]
that's great, thanks a lot @marcolardera

**Pull request closed without merging**
