### PR TITLE
logger support

### PR DESCRIPTION
**Pull request by moxious**
This PR proposes to silence most `console` output in favor of `logging` output, which is more configurable in a standard pythonic way.

What you lose is some of the bold/colored output (logger doesn't usually do that).  What you gain is a lot of flexibility with config of the library, we can arbitrarily silence things with the --log-level command flag now, and if we wanted we can change the default formatter for the message so that the message would come with information about what time the message was generated, what part of the code, etc.  (See logging docs).

With the `-n` flag I introduced recently, you'll see all of the conditional ifs have been taken out.  At the beginning of main, if you're running the program non-interactively, I just set the log level to WARN to silence all of the regular output.  That's the sort of thing logging lib can do.

Later modes could be introduced that would log messages in any other format, see here: https://docs.python.org/3/howto/logging.html#changing-the-format-of-displayed-messages

### CODE REVIEW

**Comment by marcolardera** [comment]
Thank you @moxious . Your points are valid, but why not using the Rich logging handler? (https://rich.readthedocs.io/en/stable/logging.html)

In this way we can have both the colors/bolds/etc and the log level configuration...

**Comment by marcolardera** [comment]
I experimented with the Rich logger a little bit. It seemed promising but unfortunately there is a major issue: it can't render the Markdown response. The same problem, anyway, exists with the standard Python logger:

Screenshot from 2023-11-11 15-55-56

The Markdown rendering is such a useful feature (for code, tables, etc) that I think it would be harmful to drop, even considering the benefits of logging vs printing. Thus, unless I'm missing something, I think it's better not to merge this PR for now...

**Comment by moxious** [comment]
at your option.  I think the logger module is better because it's so standard and understood by other developers.  Colors and markdown are useful **iff** you're in interactive mode, but one of the aspects of well-behaved command-line tools is that they work well in either mode, hence the pipeline support and so on.  

Ofc if you don't use a logger of some sort, you'll still have the issue of not being able to selectively mute messages emitted in different scenarios.

**Comment by marcolardera** [comment]
In the end I realized the obvious: I can use logging with the RichHandler for all the messages *except* for the ChatGPT responses (that should never be silenced even in non interactive mode, so it's not an issue).

Therefore I pushed the change with this commit: https://github.com/marcolardera/chatgpt-cli/commit/e59614ae66af89131e11405adf3f7f02fb3392cb

It's similar to your branch with the only difference of using RichHandler instead of the default Python logger. So now we have the best of both worlds: colors & formatting as well as the possibility of setting log levels. @moxious

**Pull request closed without merging**
