### PR TITLE
Wrap into package with setuptools

### PR DESCRIPTION
**Pull request by SiKreuz**
I wrapped the program into a package using setuptools. Now it is super easy to install this repo with a single pip command.

This also addresses #30 as the config file is moved to a default directory according to XDG base directory specification.

### CODE REVIEW

**Comment by SiKreuz** [comment]
To try it out from this branch use this command for installation instead.
```console
pip install git+https://github.com/SiKreuz/chatgpt-cli@package
```

**Comment by SiKreuz** [comment]
@marcolardera I'm using my Mac, so it's definitely working on MacOS. 
On MacOS I get my config file stored in `~/.config/chatgpt-cli/config.yaml`. Same for linux. I cannot check it right now for Windows so please do that if you can.

I also thought about using [`appdirs`](https://pypi.org/project/appdirs/) library. I didn't like that it didn't use `~/.config/chatgpt-cli/config.yaml` on MacOS. But it might be worth to look into that library again. I think it's a bit better developed than the other one. What do you think?

**Comment by marcolardera** [comment]
> To try it out from this branch use this command for installation instead.
> 
> ```
> pip install git+https://github.com/SiKreuz/chatgpt-cli@package
> ```

I'm trying this. If I run this in a venv, everything seems fine, i can then run the package just typing `chatgpt-cli`. However, if I install it globally (the most common case for a user), I get this error:

```
liutprand@liutprand-desktop:~$ chatgpt-cli
Traceback (most recent call last):
  File "/home/liutprand/.local/bin/chatgpt-cli", line 5, in <module>
    from chatgpt import main
ModuleNotFoundError: No module named 'chatgpt'
```

It seems like the package has not been added to my site-packages folder. Do you have any idea why?

**Comment by SiKreuz** [comment]
@marcolardera What OS are you using? On my MacOS it's working perfectly fine. Did you have a look at your side-packages folder. Is there something in there?

**Comment by SiKreuz** [comment]
@marcolardera Yeah no rush. I will also give it a try on my Linux machines in the next days.

**Comment by marcolardera** [comment]
Hi @SiKreuz , I finally fixed my issue and merged the PR, with the additional contribution of @christian-oudard (the only difference is that all the files - config, prompt history and session history - are in the same $XDG_CONFIG_HOME folder)

**Comment by SiKreuz** [comment]
Hey @marcolardera, that sounds great. Thanks for looking into it and merging! :)

**Pull request merged**
